### ISSUE TITLE
drbd-loader for noble (24.04) exists and link broken

### ISSUE THREAD

**Issue by modzilla99** [piraeusdatastore/docs#1]
Hey there,

the link to the docs on the main piraeus website does not redirect to the new docs. Also I have noticed that the drbd-loader is also available for Ubuntu 24.04 (noble), but it is not advertised in the docs. [quay.io/piraeusdatastore/drbd9-noble](https://quay.io/piraeusdatastore/drbd9-jammy)

**Comment by WanzenBug** [comment]
The updated page is still work in progress. I'll make sure to fix the mentioned missing link.
